package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class ProcessTrainTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _value;

    protected String _var;

    @Override
    public String getComponentType() {
        return "ProcessTrainComponent";
    }

    @Override
    public String getRendererType() {
        return "ProcessTrainRenderer";
    }

    public void setValue(String aValue) {
        _value = aValue;
    }

    public void setVar(String aValue) {
        _var = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "value", _value);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "var", _var);
    }

    @Override
    public void release() {
        super.release();
        _value = null;
        _var = null;
    }
}
