package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class TableTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _value;

    protected String _var;

    protected String _functionsAlign;

    protected String _showHeader;

    protected String _showFooter;

    protected String _useStyles;

    protected String _fillupRows;

    protected String _first;

    protected String _rows;

    @Override
    public String getComponentType() {
        return "TableComponent";
    }

    @Override
    public String getRendererType() {
        return "TableRenderer";
    }

    public void setValue(String aValue) {
        _value = aValue;
    }

    public void setVar(String aValue) {
        _var = aValue;
    }

    public void setFunctionsAlign(String aValue) {
        _functionsAlign = aValue;
    }

    public void setShowHeader(String aValue) {
        _showHeader = aValue;
    }

    public void setShowFooter(String aValue) {
        _showFooter = aValue;
    }

    public void setUseStyles(String aValue) {
        _useStyles = aValue;
    }

    public void setFillupRows(String aValue) {
        _fillupRows = aValue;
    }

    public void setFirst(String aValue) {
        _first = aValue;
    }

    public void setRows(String aValue) {
        _rows = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "value", _value);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "var", _var);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "functionsAlign", _functionsAlign);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "showHeader", _showHeader);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "showFooter", _showFooter);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "useStyles", _useStyles);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "fillupRows", _fillupRows);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "first", _first);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "rows", _rows);
    }

    @Override
    public void release() {
        super.release();
        _value = null;
        _var = null;
        _functionsAlign = null;
        _showHeader = null;
        _showFooter = null;
        _useStyles = null;
        _fillupRows = null;
        _first = null;
        _rows = null;
    }
}
