package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class GridbagLayoutCellTagBase extends de.mogwai.common.web.component.taglib.jsp.LogableTag {

    protected String _x;

    protected String _y;

    protected String _width;

    protected String _height;

    protected String _align;

    protected String _valign;

    @Override
    public String getComponentType() {
        return "GridbagLayoutCellComponent";
    }

    @Override
    public String getRendererType() {
        return "GridbagLayoutCellRenderer";
    }

    public void setX(String aValue) {
        _x = aValue;
    }

    public void setY(String aValue) {
        _y = aValue;
    }

    public void setWidth(String aValue) {
        _width = aValue;
    }

    public void setHeight(String aValue) {
        _height = aValue;
    }

    public void setAlign(String aValue) {
        _align = aValue;
    }

    public void setValign(String aValue) {
        _valign = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "x", _x);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "y", _y);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "width", _width);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "height", _height);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "align", _align);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "valign", _valign);
    }

    @Override
    public void release() {
        super.release();
        _x = null;
        _y = null;
        _width = null;
        _height = null;
        _align = null;
        _valign = null;
    }
}
