package de.mogwai.common.web.component.taglib.jsp.input;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class NumberInputfieldTagBase extends de.mogwai.common.web.component.taglib.jsp.input.BaseInputTag {

    protected String _numberFormatResourceKey;

    @Override
    public String getComponentType() {
        return "NumberInputfieldComponent";
    }

    @Override
    public String getRendererType() {
        return "NumberInputfieldRenderer";
    }

    public void setNumberFormatResourceKey(String aValue) {
        _numberFormatResourceKey = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "numberFormatResourceKey",
                _numberFormatResourceKey);
    }

    @Override
    public void release() {
        super.release();
        _numberFormatResourceKey = null;
    }
}
