package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class IncludeTagBase extends de.mogwai.common.web.component.taglib.jsp.LogableTag {

    protected String _page;

    protected String _var;

    protected String _value;

    @Override
    public String getComponentType() {
        return "IncludeComponent";
    }

    @Override
    public String getRendererType() {
        return "IncludeRenderer";
    }

    public void setPage(String aValue) {
        _page = aValue;
    }

    public void setVar(String aValue) {
        _var = aValue;
    }

    public void setValue(String aValue) {
        _value = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "page", _page);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "var", _var);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "value", _value);
    }

    @Override
    public void release() {
        super.release();
        _page = null;
        _var = null;
        _value = null;
    }
}
