package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class ModalTagBase extends javax.faces.webapp.UIComponentTag {

    @Override
    public String getComponentType() {
        return "ModalComponent";
    }

    @Override
    public String getRendererType() {
        return "ModalRenderer";
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
    }

    @Override
    public void release() {
        super.release();
    }
}
