package de.mogwai.common.web.component.taglib.jsp.input;

import javax.faces.component.UIComponent;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class EMailInputfieldTagBase extends de.mogwai.common.web.component.taglib.jsp.input.BaseInputTag {

    @Override
    public String getComponentType() {
        return "EMailInputfieldComponent";
    }

    @Override
    public String getRendererType() {
        return "EMailInputfieldRenderer";
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
    }

    @Override
    public void release() {
        super.release();
    }
}
