package de.mogwai.common.web.component.input;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class ComboboxComponentBase extends de.mogwai.common.web.component.input.BaseInputComponent {

    public static final String FAMILY_NAME = "MogwaiInputFamily";

    public static final String COMPONENT_TYPE = "ComboboxComponent";

    public static final String RENDERER_TYPE = "ComboboxRenderer";

    protected String _display;

    protected Boolean _nullable;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setDisplay(String aValue) {
        _display = aValue;
    }

    public String getDisplay() {
        if (_display != null) {
            return _display;
        }
        ValueBinding theBinding = getValueBinding("display");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setNullable(Boolean aValue) {
        _nullable = aValue;
    }

    public void setNullable(boolean aValue) {
        _nullable = aValue;
    }

    public boolean isNullable() {
        if (_nullable != null) {
            return _nullable.booleanValue();
        }
        ValueBinding theBinding = getValueBinding("nullable");
        if (theBinding == null) {
            return true;
        }
        Boolean theValue = (Boolean) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return true;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_display);
        theResult.add(_nullable);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _display = (String) theResult[1];
        _nullable = (Boolean) theResult[2];
    }
}
