package de.mogwai.common.web.component.input;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class RadiobuttonComponentBase extends de.mogwai.common.web.component.input.LabeledComponent {

    public static final String FAMILY_NAME = "MogwaiInputFamily";

    public static final String COMPONENT_TYPE = "RadiobuttonComponent";

    public static final String RENDERER_TYPE = "RadiobuttonRenderer";

    protected String _selectedif;

    protected Boolean _selected;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setSelectedif(String aValue) {
        _selectedif = aValue;
    }

    public String getSelectedif() {
        if (_selectedif != null) {
            return _selectedif;
        }
        ValueBinding theBinding = getValueBinding("selectedif");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setSelected(Boolean aValue) {
        _selected = aValue;
    }

    public void setSelected(boolean aValue) {
        _selected = aValue;
    }

    public boolean isSelected() {
        if (_selected != null) {
            return _selected.booleanValue();
        }
        ValueBinding theBinding = getValueBinding("selected");
        if (theBinding == null) {
            return false;
        }
        Boolean theValue = (Boolean) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return false;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_selectedif);
        theResult.add(_selected);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _selectedif = (String) theResult[1];
        _selected = (Boolean) theResult[2];
    }
}
