package de.mogwai.common.web.component.layout;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class ScrollComponentBase extends javax.faces.component.UIComponentBase {

    public static final String FAMILY_NAME = "MogwaiGroupingFamily";

    public static final String COMPONENT_TYPE = "ScrollComponent";

    public static final String RENDERER_TYPE = "ScrollRenderer";

    protected Integer _scrollTop;

    protected Integer _scrollLeft;

    protected Boolean _saveScrollState;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setScrollTop(Integer aValue) {
        _scrollTop = aValue;
    }

    public Integer getScrollTop() {
        if (_scrollTop != null) {
            return _scrollTop;
        }
        ValueBinding theBinding = getValueBinding("scrollTop");
        if (theBinding == null) {
            return null;
        }
        Integer theValue = (Integer) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setScrollLeft(Integer aValue) {
        _scrollLeft = aValue;
    }

    public Integer getScrollLeft() {
        if (_scrollLeft != null) {
            return _scrollLeft;
        }
        ValueBinding theBinding = getValueBinding("scrollLeft");
        if (theBinding == null) {
            return null;
        }
        Integer theValue = (Integer) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setSaveScrollState(Boolean aValue) {
        _saveScrollState = aValue;
    }

    public void setSaveScrollState(boolean aValue) {
        _saveScrollState = aValue;
    }

    public boolean isSaveScrollState() {
        if (_saveScrollState != null) {
            return _saveScrollState.booleanValue();
        }
        ValueBinding theBinding = getValueBinding("saveScrollState");
        if (theBinding == null) {
            return false;
        }
        Boolean theValue = (Boolean) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return false;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_scrollTop);
        theResult.add(_scrollLeft);
        theResult.add(_saveScrollState);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _scrollTop = (Integer) theResult[1];
        _scrollLeft = (Integer) theResult[2];
        _saveScrollState = (Boolean) theResult[3];
    }
}
