package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class LinkTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _rel;

    protected String _type;

    protected String _href;

    @Override
    public String getComponentType() {
        return "LinkComponent";
    }

    @Override
    public String getRendererType() {
        return "LinkRenderer";
    }

    public void setRel(String aValue) {
        _rel = aValue;
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public void setHref(String aValue) {
        _href = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "rel", _rel);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "type", _type);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "href", _href);
    }

    @Override
    public void release() {
        super.release();
        _rel = null;
        _type = null;
        _href = null;
    }
}
