package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class VelocityTemplateTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _template;

    @Override
    public String getComponentType() {
        return "VelocityTemplateComponent";
    }

    @Override
    public String getRendererType() {
        return "VelocityTemplateRenderer";
    }

    public void setTemplate(String aValue) {
        _template = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "template", _template);
    }

    @Override
    public void release() {
        super.release();
        _template = null;
    }
}
