package de.mogwai.common.web.component.action;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class CommandLinkComponentBase extends de.mogwai.common.web.component.action.AbstractCommandComponent {

    public static final String FAMILY_NAME = "MogwaiActionFamily";

    public static final String COMPONENT_TYPE = "CommandLinkComponent";

    public static final String RENDERER_TYPE = "CommandLinkRenderer";

    protected Boolean _keySensitive;

    protected Integer _actionKey;

    protected String _styleClass;

    protected String _title;

    protected String _titleKey;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setKeySensitive(Boolean aValue) {
        _keySensitive = aValue;
    }

    public void setKeySensitive(boolean aValue) {
        _keySensitive = aValue;
    }

    public boolean isKeySensitive() {
        if (_keySensitive != null) {
            return _keySensitive.booleanValue();
        }
        ValueBinding theBinding = getValueBinding("keySensitive");
        if (theBinding == null) {
            return false;
        }
        Boolean theValue = (Boolean) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return false;
        }
        return theValue;
    }

    public void setActionKey(Integer aValue) {
        _actionKey = aValue;
    }

    public void setActionKey(int aValue) {
        _actionKey = aValue;
    }

    public int getActionKey() {
        if (_actionKey != null) {
            return _actionKey.intValue();
        }
        ValueBinding theBinding = getValueBinding("actionKey");
        if (theBinding == null) {
            return 13;
        }
        Number theValue = (Number) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return 13;
        }
        return theValue.intValue();
    }

    public void setStyleClass(String aValue) {
        _styleClass = aValue;
    }

    public String getStyleClass() {
        if (_styleClass != null) {
            return _styleClass;
        }
        ValueBinding theBinding = getValueBinding("styleClass");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setTitle(String aValue) {
        _title = aValue;
    }

    public String getTitle() {
        if (_title != null) {
            return _title;
        }
        ValueBinding theBinding = getValueBinding("title");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setTitleKey(String aValue) {
        _titleKey = aValue;
    }

    public String getTitleKey() {
        if (_titleKey != null) {
            return _titleKey;
        }
        ValueBinding theBinding = getValueBinding("titleKey");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_keySensitive);
        theResult.add(_actionKey);
        theResult.add(_styleClass);
        theResult.add(_title);
        theResult.add(_titleKey);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _keySensitive = (Boolean) theResult[1];
        _actionKey = (Integer) theResult[2];
        _styleClass = (String) theResult[3];
        _title = (String) theResult[4];
        _titleKey = (String) theResult[5];
    }
}
