package de.mogwai.common.web.component.layout;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class TitledBoxComponentBase extends javax.faces.component.UIComponentBase {

    public static final String FAMILY_NAME = "MogwaiGroupingFamily";

    public static final String COMPONENT_TYPE = "TitledBoxComponent";

    public static final String RENDERER_TYPE = "TitledBoxRenderer";

    protected String _label;

    protected String _key;

    protected String _type;

    protected String _cssprefix;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setLabel(String aValue) {
        _label = aValue;
    }

    public String getLabel() {
        if (_label != null) {
            return _label;
        }
        ValueBinding theBinding = getValueBinding("label");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setKey(String aValue) {
        _key = aValue;
    }

    public String getKey() {
        if (_key != null) {
            return _key;
        }
        ValueBinding theBinding = getValueBinding("key");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public String getType() {
        if (_type != null) {
            return _type;
        }
        ValueBinding theBinding = getValueBinding("type");
        if (theBinding == null) {
            return "titledbox";
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return "titledbox";
        }
        return theValue;
    }

    public void setCssprefix(String aValue) {
        _cssprefix = aValue;
    }

    public String getCssprefix() {
        if (_cssprefix != null) {
            return _cssprefix;
        }
        ValueBinding theBinding = getValueBinding("cssprefix");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_label);
        theResult.add(_key);
        theResult.add(_type);
        theResult.add(_cssprefix);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _label = (String) theResult[1];
        _key = (String) theResult[2];
        _type = (String) theResult[3];
        _cssprefix = (String) theResult[4];
    }
}
