package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class ScrollTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _scrollTop;

    protected String _scrollLeft;

    protected String _saveScrollState;

    @Override
    public String getComponentType() {
        return "ScrollComponent";
    }

    @Override
    public String getRendererType() {
        return "ScrollRenderer";
    }

    public void setScrollTop(String aValue) {
        _scrollTop = aValue;
    }

    public void setScrollLeft(String aValue) {
        _scrollLeft = aValue;
    }

    public void setSaveScrollState(String aValue) {
        _saveScrollState = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "scrollTop", _scrollTop);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "scrollLeft", _scrollLeft);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "saveScrollState", _saveScrollState);
    }

    @Override
    public void release() {
        super.release();
        _scrollTop = null;
        _scrollLeft = null;
        _saveScrollState = null;
    }
}
