package de.mogwai.common.web.component.common;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class ScriptComponentBase extends javax.faces.component.UIComponentBase {

    public static final String FAMILY_NAME = "MogwaiGroupingFamily";

    public static final String COMPONENT_TYPE = "ScriptComponent";

    public static final String RENDERER_TYPE = "ScriptRenderer";

    protected String _type;

    protected String _src;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public String getType() {
        if (_type != null) {
            return _type;
        }
        ValueBinding theBinding = getValueBinding("type");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    public void setSrc(String aValue) {
        _src = aValue;
    }

    public String getSrc() {
        if (_src != null) {
            return _src;
        }
        ValueBinding theBinding = getValueBinding("src");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_type);
        theResult.add(_src);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _type = (String) theResult[1];
        _src = (String) theResult[2];
    }
}
