package de.mogwai.common.web.component.taglib.jsp.action;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class CommandLinkTagBase extends de.mogwai.common.web.component.taglib.jsp.action.AbstractCommandTag {

    protected String _keySensitive;

    protected String _actionKey;

    protected String _styleClass;

    protected String _title;

    protected String _titleKey;

    @Override
    public String getComponentType() {
        return "CommandLinkComponent";
    }

    @Override
    public String getRendererType() {
        return "CommandLinkRenderer";
    }

    public void setKeySensitive(String aValue) {
        _keySensitive = aValue;
    }

    public void setActionKey(String aValue) {
        _actionKey = aValue;
    }

    public void setStyleClass(String aValue) {
        _styleClass = aValue;
    }

    public void setTitle(String title) {
        this._title = title;
    }

    public void setTitleKey(String titleKey) {
        this._titleKey = titleKey;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "keySensitive", _keySensitive);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "actionKey", _actionKey);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "styleClass", _styleClass);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "title", _title);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "titleKey", _titleKey);
    }

    @Override
    public void release() {
        super.release();
        _keySensitive = null;
        _actionKey = null;
        _styleClass = null;
    }
}
