package de.mogwai.common.web.component.taglib.jsp.input;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class RadiobuttonTagBase extends de.mogwai.common.web.component.taglib.jsp.input.LabeledComponentTag {

    protected String _selectedif;

    protected String _selected;

    @Override
    public String getComponentType() {
        return "RadiobuttonComponent";
    }

    @Override
    public String getRendererType() {
        return "RadiobuttonRenderer";
    }

    public void setSelectedif(String aValue) {
        _selectedif = aValue;
    }

    public void setSelected(String aValue) {
        _selected = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "selectedif", _selectedif);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "selected", _selected);
    }

    @Override
    public void release() {
        super.release();
        _selectedif = null;
        _selected = null;
    }
}
