package de.mogwai.common.web.component.taglib.jsp.input;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class ComboboxTagBase extends de.mogwai.common.web.component.taglib.jsp.input.BaseInputTag {

    protected String _display;

    protected String _nullable;

    protected String _values;

    @Override
    public String getComponentType() {
        return "ComboboxComponent";
    }

    @Override
    public String getRendererType() {
        return "ComboboxRenderer";
    }

    public void setDisplay(String aValue) {
        _display = aValue;
    }

    public void setNullable(String aValue) {
        _nullable = aValue;
    }

    public void setValues(String aValue) {
        _values = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "display", _display);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "nullable", _nullable);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "values", _values);
    }

    @Override
    public void release() {
        super.release();
        _display = null;
        _nullable = null;
        _values = null;
    }
}
