package de.mogwai.common.web.component.common;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class FacetComponentBase extends javax.faces.component.UIColumn {

    public static final String FAMILY_NAME = "MogwaiGroupingFamily";

    public static final String COMPONENT_TYPE = "FacetComponent";

    public static final String RENDERER_TYPE = "null";

    protected String _name;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setName(String aValue) {
        _name = aValue;
    }

    public String getName() {
        if (_name != null) {
            return _name;
        }
        ValueBinding theBinding = getValueBinding("name");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_name);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _name = (String) theResult[1];
    }
}
