package de.mogwai.common.web.component.taglib.jsp.action;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class CommandButtonTagBase extends de.mogwai.common.web.component.taglib.jsp.action.AbstractCommandTag {

    protected String _value;

    protected String _key;

    protected String _type;

    protected String _keySensitive;

    protected String _actionKey;

    protected String _width;

    protected String _sizeToGridBag;

    @Override
    public String getComponentType() {
        return "CommandButtonComponent";
    }

    @Override
    public String getRendererType() {
        return "CommandButtonRenderer";
    }

    public void setValue(String aValue) {
        _value = aValue;
    }

    public void setKey(String aValue) {
        _key = aValue;
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public void setKeySensitive(String aValue) {
        _keySensitive = aValue;
    }

    public void setActionKey(String aValue) {
        _actionKey = aValue;
    }

    public void setWidth(String aValue) {
        _width = aValue;
    }

    public void setSizeToGridBag(String aValue) {
        _sizeToGridBag = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "value", _value);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "key", _key);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "type", _type);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "keySensitive", _keySensitive);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "actionKey", _actionKey);
        UIComponentTagUtils.setIntegerProperty(getFacesContext(), aComponent, "width", _width);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "sizeToGridBag", _sizeToGridBag);
    }

    @Override
    public void release() {
        super.release();
        _value = null;
        _key = null;
        _type = null;
        _keySensitive = null;
        _actionKey = null;
        _width = null;
        _sizeToGridBag = null;
    }
}
