package de.mogwai.common.web.component.layout;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class TitleComponentBase extends javax.faces.component.UIOutput {

    public static final String FAMILY_NAME = "MogwaiGroupingFamily";

    public static final String COMPONENT_TYPE = "TitleComponent";

    public static final String RENDERER_TYPE = "TitleRenderer";

    protected String _title;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setTitle(String aValue) {
        _title = aValue;
    }

    public String getTitle() {
        if (_title != null) {
            return _title;
        }
        ValueBinding theBinding = getValueBinding("title");
        if (theBinding == null) {
            return null;
        }
        String theValue = (String) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return null;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_title);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _title = (String) theResult[1];
    }
}
