package de.mogwai.common.web.component.action;

import java.util.Vector;

import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER ! Generated at Sun Dec 16
 * 11:38:15 CET 2007
 */
public abstract class AbstractCommandComponentBase extends javax.faces.component.UICommand {

    public static final String FAMILY_NAME = "MogwaiActionFamily";

    public static final String COMPONENT_TYPE = "AbstractCommandComponent";

    public static final String RENDERER_TYPE = "AbstractCommandRenderer";

    protected Boolean _disabled;

    @Override
    public String getFamily() {
        return FAMILY_NAME;
    }

    public void setDisabled(Boolean aValue) {
        _disabled = aValue;
    }

    public void setDisabled(boolean aValue) {
        _disabled = aValue;
    }

    public boolean isDisabled() {
        if (_disabled != null) {
            return _disabled.booleanValue();
        }
        ValueBinding theBinding = getValueBinding("disabled");
        if (theBinding == null) {
            return false;
        }
        Boolean theValue = (Boolean) theBinding.getValue(getFacesContext());
        if (theValue == null) {
            return false;
        }
        return theValue;
    }

    @Override
    public Object saveState(FacesContext aContext) {
        Vector<Object> theResult = new Vector<Object>();
        theResult.add(super.saveState(aContext));
        theResult.add(_disabled);
        return theResult.toArray();
    }

    @Override
    public void restoreState(FacesContext aContext, Object aState) {
        Object[] theResult = (Object[]) aState;
        super.restoreState(aContext, theResult[0]);
        _disabled = (Boolean) theResult[1];
    }
}
