package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class MessagesTagBase extends org.apache.myfaces.taglib.html.HtmlMessagesTag {

    @Override
    public String getComponentType() {
        return "MessagesComponent";
    }

    @Override
    public String getRendererType() {
        return "MessagesRenderer";
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
    }

    @Override
    public void release() {
        super.release();
    }
}
