package de.mogwai.common.web.component.taglib.jsp.layout;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class TitledBoxTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _label;

    protected String _key;

    protected String _type;

    protected String _cssprefix;

    @Override
    public String getComponentType() {
        return "TitledBoxComponent";
    }

    @Override
    public String getRendererType() {
        return "TitledBoxRenderer";
    }

    public void setLabel(String aValue) {
        _label = aValue;
    }

    public void setKey(String aValue) {
        _key = aValue;
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public void setCssprefix(String aValue) {
        _cssprefix = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "label", _label);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "key", _key);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "type", _type);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "cssprefix", _cssprefix);
    }

    @Override
    public void release() {
        super.release();
        _label = null;
        _key = null;
        _type = null;
        _cssprefix = null;
    }
}
