package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class FacetTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _name;

    @Override
    public String getComponentType() {
        return "FacetComponent";
    }

    @Override
    public String getRendererType() {
        return "null";
    }

    public void setName(String aValue) {
        _name = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "name", _name);
    }

    @Override
    public void release() {
        super.release();
        _name = null;
    }
}
