package de.mogwai.common.web.component.taglib.jsp.common;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class ScriptTagBase extends javax.faces.webapp.UIComponentTag {

    protected String _type;

    protected String _src;

    @Override
    public String getComponentType() {
        return "ScriptComponent";
    }

    @Override
    public String getRendererType() {
        return "ScriptRenderer";
    }

    public void setType(String aValue) {
        _type = aValue;
    }

    public void setSrc(String aValue) {
        _src = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "type", _type);
        UIComponentTagUtils.setStringProperty(getFacesContext(), aComponent, "src", _src);
    }

    @Override
    public void release() {
        super.release();
        _type = null;
        _src = null;
    }
}
