package de.mogwai.common.web.component.taglib.jsp.action;

import javax.faces.component.UIComponent;

import org.apache.myfaces.shared_impl.taglib.UIComponentTagUtils;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class AbstractCommandTagBase extends de.mogwai.common.web.component.taglib.jsp.LogableTag {

    protected String _action;

    protected String _immediate;

    protected String _disabled;

    @Override
    public String getComponentType() {
        return "AbstractCommandComponent";
    }

    @Override
    public String getRendererType() {
        return "AbstractCommandRenderer";
    }

    public void setAction(String aValue) {
        _action = aValue;
    }

    public void setImmediate(String aValue) {
        _immediate = aValue;
    }

    public void setDisabled(String aValue) {
        _disabled = aValue;
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
        UIComponentTagUtils.setActionProperty(getFacesContext(), aComponent, _action);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "immediate", _immediate);
        UIComponentTagUtils.setBooleanProperty(getFacesContext(), aComponent, "disabled", _disabled);
    }

    @Override
    public void release() {
        super.release();
        _action = null;
        _immediate = null;
        _disabled = null;
    }
}
