package de.mogwai.common.web.component.taglib.jsp.action;

import javax.faces.component.UIComponent;

/**
 * Automatically Generated By JSFCodeGen. DO NOT ALTER !
 */
public abstract class PageRefreshTagBase extends de.mogwai.common.web.component.taglib.jsp.action.AbstractCommandTag {

    @Override
    public String getComponentType() {
        return "PageRefreshComponent";
    }

    @Override
    public String getRendererType() {
        return "PageRefreshRenderer";
    }

    @Override
    protected void setProperties(UIComponent aComponent) {
        super.setProperties(aComponent);
    }

    @Override
    public void release() {
        super.release();
    }
}
